[build]
  command = "npm run init; gulp all"
  functions = "lambda"
  publish = "build"

[context.production]
  command = "npm run init; gulp all -p"

[dev]
  command = "gulp"
  port = 3000
  publish = "build"